### ISSUE TITLE
Deploy site for internal review

### ISSUE THREAD

**Issue by meshulam** [codaco/feedback-site#2]
Step 1: one-off manual deploy, on a subdomain?

Step 2: Ansible role or other commands for deploying the feedback site reliably

**Comment by meshulam** [comment]
The standard way to deploy Meteor apps is with [mup](https://github.com/zodern/meteor-up), which runs Node and Mongo in a docker container. When I tried to run mup to set up the server, I got an error:

```
Your Linux kernel version 2.6.32-042stab111.12 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer.
```

I raised the issue of the hosting provider's very out-of-date kernel previously, but now it's actually posing a practical problem. The two options I see are:

1. Host this app on another provider like DigitalOcean. Could cost as little as $5/month
2. Look into less-standard deployment options that don't use Docker

Meteor tries to be very all-in-the-box and I'd like to stay on their Docker happy path if possible. @jthrilly what do you think?

**Comment by jthrilly** [comment]
The answer we got at the time from the host about this old Kernel was fine, but clearly if it stops us doing what we need to it isn't good enough. @meshulam - am I correct in thinking that you are added as a technical contact on our hosting provider? Could you raise this in a support ticket with them? If not, let me know and I will take care of it.

I am reluctant to move host since I don't want to manage two providers if we can help it.

If/when we get this sorted, I'd like this platform on feedback.networkcanvas.com please.

**Comment by meshulam** [comment]
@jthrilly I don't think I've been given any special access to the hosting provider. Not sure what they'll be able to do about it if this is what their infrastructure is. But can you go ahead and ask them?

**Comment by jthrilly** [comment]
@meshulam - I've contacted the host and will let you know ASAP what they say. The only option they offered before was a destructive re-provisioning to a different KVM. If this were the only option, would it take a significant amount of time for you to set us up again? We would want to synchronise with you and the host to minimise downtime.

**Comment by meshulam** [comment]
We're now deployed on the VPS. Not checking the deploy config into git for now, but I think it will be safe to do so.
